name: hquality
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  camera: ^0.10.0+4
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  mime: ^1.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^4.0.0
  mockito: ^5.0.0
  test: ^1.24.9

flutter:
  assets:
    - assets/images/unknown_user.png
    - lib/l10n/translations.json
    - .env
  uses-material-design: true