// Mocks generated by Mockito 5.4.4 from annotations
// in hquality/test/l10n/language_picker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i4;

import 'package:flutter/material.dart' as _i2;
import 'package:hquality/l10n/l10n.dart' as _i3;
import 'package:hquality/storage/storage.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [L10n].
///
/// See the documentation for Mockito's code generation for more information.
class MockL10n extends _i1.Mock implements _i3.L10n {
  MockL10n() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Locale> get supportedLocales => (super.noSuchMethod(
        Invocation.getter(#supportedLocales),
        returnValue: <_i4.Locale>[],
      ) as List<_i4.Locale>);

  @override
  _i5.Future<void> loadTranslations() => (super.noSuchMethod(
        Invocation.method(
          #loadTranslations,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String translate(
    String? key,
    String? locale,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #translate,
          [
            key,
            locale,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #translate,
            [
              key,
              locale,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i7.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<dynamic> get storageNotifier => (super.noSuchMethod(
        Invocation.getter(#storageNotifier),
        returnValue: _FakeValueNotifier_0<dynamic>(
          this,
          Invocation.getter(#storageNotifier),
        ),
      ) as _i2.ValueNotifier<dynamic>);

  @override
  dynamic get(String? key) => super.noSuchMethod(Invocation.method(
        #get,
        [key],
      ));

  @override
  void remove({
    required String? key,
    bool? updateNotifier = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {
            #key: key,
            #updateNotifier: updateNotifier,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void set({
    required String? key,
    required dynamic obj,
    bool? updateNotifier = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #set,
          [],
          {
            #key: key,
            #obj: obj,
            #updateNotifier: updateNotifier,
          },
        ),
        returnValueForMissingStub: null,
      );
}
