// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjem5rhdhJjt-dH-tge0h_i_gZCckzwlA',
    appId: '1:662504542440:web:0a69dc6afa99817a6f795d',
    messagingSenderId: '662504542440',
    projectId: 'hquality-c7c7f',
    authDomain: 'hquality-c7c7f.firebaseapp.com',
    storageBucket: 'hquality-c7c7f.appspot.com',
    measurementId: 'G-ZT1GVT2GBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKhZvOMWithxSqRl3QfkS541UDdoxYIq0',
    appId: '1:662504542440:android:cd8585bcf0b485776f795d',
    messagingSenderId: '662504542440',
    projectId: 'hquality-c7c7f',
    storageBucket: 'hquality-c7c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8R9DcKOLJmFTUFu1rFtWzrnlrVYGAgjU',
    appId: '1:662504542440:ios:d5362a00091ecd416f795d',
    messagingSenderId: '662504542440',
    projectId: 'hquality-c7c7f',
    storageBucket: 'hquality-c7c7f.appspot.com',
    iosBundleId: 'com.example.hquality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8R9DcKOLJmFTUFu1rFtWzrnlrVYGAgjU',
    appId: '1:662504542440:ios:d5362a00091ecd416f795d',
    messagingSenderId: '662504542440',
    projectId: 'hquality-c7c7f',
    storageBucket: 'hquality-c7c7f.appspot.com',
    iosBundleId: 'com.example.hquality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjem5rhdhJjt-dH-tge0h_i_gZCckzwlA',
    appId: '1:662504542440:web:bd9966d9e13fa7d06f795d',
    messagingSenderId: '662504542440',
    projectId: 'hquality-c7c7f',
    authDomain: 'hquality-c7c7f.firebaseapp.com',
    storageBucket: 'hquality-c7c7f.appspot.com',
    measurementId: 'G-S3ZHM6P7Z6',
  );
}
